Repository AY2425S2-CS2103T-F12-4/tp, pull requests merged in 2025-03, with the labels that each got.

#15 Add Terence's photo
  docs/images/terentwc.png
Labels: type.Task

#26 Update About Us Page with Kim Seung Hyun Info
  docs/AboutUs.md
Labels: type.Task, priority.High

#30 Update AboutUs with Choi Minseok's information
  docs/AboutUs.md
  docs/team/cscms03.md
Labels: priority.High

#25 Update About Us page with Wei Jian's info
  README.md
  docs/AboutUs.md
Labels: type.Task, priority.High

#28 Update AboutUs
  docs/AboutUs.md
Labels: type.Task

#57 update edit command for employee ID handling
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Task, priority.High

#52 Update Add Command to support Birthdays and WA
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/anniversary/AddAnniversaryCommandParser.java
  src/main/java/seedu/address/model/anniversary/Anniversary.java
  src/main/java/seedu/address/model/anniversary/Birthday.java
  src/main/java/seedu/address/model/anniversary/WorkAnniversary.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#75 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#73 Update index.md
  docs/index.md
Labels: type.Task, priority.High

#76 Integrate EmplyeeId
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/AddAnniversaryCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/DeleteAnniversaryCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/anniversary/AddAnniversaryCommandParser.java
  src/main/java/seedu/address/logic/parser/anniversary/DeleteAnniversaryCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/EmployeeId.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#80 Branch addresstoposition
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/AddAnniversaryCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/DeleteAnniversaryCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/JobPosition.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#77 Add CLI Implementation of Show Anniversary
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/anniversary/DeleteAnniversaryCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/ShowAnniversaryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/anniversary/ShowAnniversaryCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: type.Task, type.Bug, priority.High

#71 Add : visible UUID from PersonCard and copy paste feature
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AnniversaryParserUtils.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/anniversary/AddAnniversaryCommandParser.java
  src/main/java/seedu/address/model/anniversary/Anniversary.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedAnniversary.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.Low

#81 Update UG for Add Person and Show Anni command
  docs/UserGuide.md
Labels: priority.High

#84 add tests and fixed bugs
  build.gradle
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/AddAnniversaryCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/DeleteAnniversaryCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/anniversary/AddAnniversaryCommandParser.java
  src/main/java/seedu/address/logic/parser/anniversary/DeleteAnniversaryCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddAnniversaryCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAnniversaryCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAnniversaryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAnniversaryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Bug, severity.High

#97 Update UserGuide
  docs/UserGuide.md
  docs/images/HelpU.png
Labels: priority.High

#87 Edit bug fixes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Bug, priority.High

#108 Add : UML diagram and User Guide Update
  docs/UserGuide.md
  docs/diagrams/AddAnniversaryCommandDiagram.puml
  docs/diagrams/AddAnniversaryCommandSequenceDiagram.puml
  docs/diagrams/DeleteAnniversaryCommandDiagram.puml
  docs/diagrams/DeleteAnniversaryCommandSequenceDiagram.puml
  docs/diagrams/ExportDiagram.puml
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/ImportDiagram.puml
  docs/diagrams/ImportSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/anniversary/AddAnniversaryCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/DeleteAnniversaryCommand.java
Labels: priority.High
