Repository AY2425S2-CS2103T-F12-4/tp, pull requests merged in 2025-04, with the labels that each got.

#115 Remove extra tags generator from PersonCard constructor
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Bug

#147 Fixes to Find Command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/PersonSearchPredicateBuilder.java
  src/main/java/seedu/address/logic/parser/anniversary/ShowAnniversaryCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ShowAnniversaryCommandParserTest.java
Labels: type.Bug, priority.High, alpha-bug

#143 Fix employee id prefix list from observable
  docs/UserGuide.md
  docs/diagrams/AddAnniversaryCommandSequenceDiagram.puml
  docs/diagrams/DeleteAnniversaryCommandSequenceDiagram.puml
  jsdlfakjsdfladsf/dfadfa.csv
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/AddAnniversaryCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/DeleteAnniversaryCommand.java
  src/main/java/seedu/address/logic/commands/anniversary/ShowAnniversaryCommand.java
  src/main/java/seedu/address/logic/commands/importexport/ImportCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Employee.java
  src/main/java/seedu/address/model/person/EmployeeId.java
  src/main/java/seedu/address/model/person/UniqueEmployeeList.java
  src/main/java/seedu/address/model/util/EmployeeIdPrefixValidationUtils.java
  src/test/data/ImportCommandTest/testEmployeeIdPrefixConflict.csv
  src/test/data/ImportCommandTest/testEmployeeIdPrefixConflict.json
  src/test/java/seedu/address/logic/commands/AddEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowAnniversaryCommandTest.java
  src/test/java/seedu/address/logic/commands/anniversary/AddAnniversaryCommandTest.java
  src/test/java/seedu/address/logic/commands/anniversary/DeleteAnniversaryCommandTest.java
  src/test/java/seedu/address/logic/commands/importexport/ImportCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/importexport/ImportCommandTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#167 Change Addressbook to Hreers
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/Hreers.png
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#168 Dg
  docs/UserGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/importexport/AddressBookFormatConverter.java
  src/main/java/seedu/address/logic/commands/importexport/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AnniversaryParserUtils.java
  src/main/java/seedu/address/storage/JsonCsvConverter.java
  src/test/java/seedu/address/logic/commands/importexport/ImportCommandIntegrationTest.java
  src/test/java/seedu/address/logic/parser/AnniversaryParserUtilsTest.java
Labels: priority.Medium

#183 Branch dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/anniversary/ShowAnniversaryCommand.java
Labels: priority.High

#270 Update UG headers except Reminders
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, beta-bug
